package license

import (
	"crypto/ed25519"
	"encoding/base64"
	"errors"
	"fmt"
)

// productionPublicKeyBase64 is the Ed25519 PUBLIC key AUK verifies signed
// licenses against. It is compiled into the binary; only the matching PRIVATE
// key can mint a license this build will accept.
//
// This is the PRODUCTION key, generated by cmd/mkkeypair for the first public
// release that takes money. Its private half exists in exactly one place: the
// licence-signing Cloudflare Worker's secret store (worker/, secret
// AUK_LICENSE_PRIVATE_KEY). It has never been committed, and the local file it
// was generated into is deleted once uploaded.
//
// The dev key that preceded it (whose private half sat in a home directory) is
// permanently retired: no build that ever reached a customer embedded it, and
// licences signed with it are rejected by this build like any other forgery.
//
// Rotating this key is a breaking change for existing customers — every
// licence already issued was signed by the old private key and will fail
// verification against a new one. Rotate only with a re-issue plan, and
// re-mint the frozen vector in verify_vector_test.go at the same time.
const productionPublicKeyBase64 = "wkKMeKKDkZP6PJvB2HAuiUjX2t+zPPG8RPAwjsmvRv0="

// ErrBadSignature is returned by verification when a SignedLicense does not
// carry a valid signature from the expected key. It intentionally does not
// distinguish "tampered" from "signed by the wrong key" from "malformed
// signature" — to an offline verifier those are the same failure: this is not
// a license we can trust.
var ErrBadSignature = errors.New("license: signature verification failed")

// embeddedPublicKey parses the compiled-in verification key. A panic here
// would mean the constant above was corrupted at edit time (a build-breaking
// programming error, not a runtime condition), so it is surfaced as an error
// the caller resolves once at construction rather than being ignored.
func embeddedPublicKey() (ed25519.PublicKey, error) {
	return parsePublicKey(productionPublicKeyBase64)
}

func parsePublicKey(b64 string) (ed25519.PublicKey, error) {
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("license: decode public key: %w", err)
	}
	if len(raw) != ed25519.PublicKeySize {
		return nil, fmt.Errorf("license: public key is %d bytes, want %d", len(raw), ed25519.PublicKeySize)
	}
	return ed25519.PublicKey(raw), nil
}

// ParsePrivateKeyBase64 decodes a base64 (standard-encoding) Ed25519 private
// key — the 64-byte form ed25519.GenerateKey returns. Used by cmd/mklicense
// (which takes the key path as a required flag) and by the licence-signing
// worker, which reads the same encoding out of its secret store.
func ParsePrivateKeyBase64(b64 string) (ed25519.PrivateKey, error) {
	raw, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("license: decode private key: %w", err)
	}
	if len(raw) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf("license: private key is %d bytes, want %d", len(raw), ed25519.PrivateKeySize)
	}
	return ed25519.PrivateKey(raw), nil
}

// Sign mints a SignedLicense by signing lic.canonicalBytes() with priv. This
// is the issuer side — cmd/mklicense and, in production, the MoR webhook. The
// running app never signs, only verifies.
func Sign(priv ed25519.PrivateKey, lic License) (SignedLicense, error) {
	if len(priv) != ed25519.PrivateKeySize {
		return SignedLicense{}, fmt.Errorf("license: private key is %d bytes, want %d", len(priv), ed25519.PrivateKeySize)
	}
	sig := ed25519.Sign(priv, lic.canonicalBytes())
	return SignedLicense{
		License:   lic,
		Alg:       "ed25519",
		Signature: base64.StdEncoding.EncodeToString(sig),
	}, nil
}

// Verify checks a SignedLicense against the embedded production public
// key. A nil return means the signature is authentic AND covers exactly these
// license fields — it says nothing about whether the license is bound to this
// machine or still within its updates window; those are separate checks in
// status.go. Any tampering with any field, or a signature from any other key,
// yields ErrBadSignature.
func Verify(sl SignedLicense) error {
	pub, err := embeddedPublicKey()
	if err != nil {
		return err
	}
	return verifyWith(pub, sl)
}

// verifyWith is the key-parameterized core of Verify, split out so tests can
// exercise the exact same verification path against an ephemeral keypair
// (no dependency on the embedded key's private half, which never lives in the
// repo) and so the Manager can be pointed at a test key.
func verifyWith(pub ed25519.PublicKey, sl SignedLicense) error {
	sig, err := base64.StdEncoding.DecodeString(sl.Signature)
	if err != nil {
		return ErrBadSignature
	}
	if len(sig) != ed25519.SignatureSize {
		return ErrBadSignature
	}
	if !ed25519.Verify(pub, sl.License.canonicalBytes(), sig) {
		return ErrBadSignature
	}
	return nil
}
