package perf

import (
	"bytes"
	"encoding/json"
	"fmt"
	"text/template"

	"apitool/internal/core"
	"apitool/internal/core/model"
)

// SummaryDelimiter brackets the JSON summary handleSummary writes to stdout,
// so the runner can pull it out of k6's other stdout noise deterministically.
const (
	summaryStart = "__APITOOL_SUMMARY_START__"
	summaryEnd   = "__APITOOL_SUMMARY_END__"
)

// scriptData is the fully-resolved, JSON-safe payload injected into the k6
// template. Every user-controlled value is passed as a JSON literal (via the
// `js` helper) rather than string-concatenated, so a quote or newline in a
// URL/header/body can't break out of the script or inject code.
type scriptData struct {
	Method      string
	URL         string
	Headers     map[string]string
	Body        string
	HasBody     bool
	OptionsJSON string
}

// GenerateScript builds a runnable k6 script from a resolved request and a
// perf config. The request is already template-expanded and auth-applied
// (core.ResolvedRequest), so this is a pure transform — no engine, no I/O.
func GenerateScript(resolved core.ResolvedRequest, cfg model.PerfConfig) (string, error) {
	headers := map[string]string{}
	for _, h := range resolved.Headers {
		if h.Enabled && h.Key != "" {
			headers[h.Key] = h.Value
		}
	}

	body := ""
	hasBody := false
	if resolved.Body != nil && resolved.Body.Kind != model.BodyNone && resolved.Body.Text != "" {
		body = resolved.Body.Text
		hasBody = true
	}

	opts, err := buildOptions(cfg)
	if err != nil {
		return "", err
	}
	optsJSON, err := json.Marshal(opts)
	if err != nil {
		return "", fmt.Errorf("marshal k6 options: %w", err)
	}

	data := scriptData{
		Method:      methodOrDefault(resolved.Method),
		URL:         resolved.URL,
		Headers:     headers,
		Body:        body,
		HasBody:     hasBody,
		OptionsJSON: string(optsJSON),
	}

	var buf bytes.Buffer
	if err := scriptTmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render k6 script: %w", err)
	}
	return buf.String(), nil
}

func methodOrDefault(m string) string {
	if m == "" {
		return "GET"
	}
	return m
}

// buildOptions maps a PerfConfig into a k6 `options` object (scenarios +
// thresholds). Kept as a plain map so json.Marshal produces valid k6 config.
func buildOptions(cfg model.PerfConfig) (map[string]any, error) {
	scenario := map[string]any{}
	switch cfg.Executor {
	case model.PerfRampingVUs:
		if len(cfg.Stages) == 0 {
			return nil, fmt.Errorf("ramping-vus requires at least one stage")
		}
		stages := make([]map[string]any, 0, len(cfg.Stages))
		for _, s := range cfg.Stages {
			if s.Duration == "" {
				return nil, fmt.Errorf("ramping-vus stage missing duration")
			}
			stages = append(stages, map[string]any{"duration": s.Duration, "target": s.Target})
		}
		scenario = map[string]any{"executor": "ramping-vus", "startVUs": 0, "stages": stages}
	case model.PerfConstantVUs, "":
		vus := cfg.VUs
		if vus <= 0 {
			vus = 1
		}
		dur := cfg.Duration
		if dur == "" {
			dur = "30s"
		}
		scenario = map[string]any{"executor": "constant-vus", "vus": vus, "duration": dur}
	default:
		return nil, fmt.Errorf("unsupported executor %q", cfg.Executor)
	}

	opts := map[string]any{
		"scenarios":             map[string]any{"default": scenario},
		"discardResponseBodies": true, // load test throughput, not body inspection
	}

	if len(cfg.Thresholds) > 0 {
		th := map[string][]string{}
		for _, t := range cfg.Thresholds {
			if t.Metric == "" || t.Expression == "" {
				continue
			}
			th[t.Metric] = append(th[t.Metric], t.Expression)
		}
		if len(th) > 0 {
			opts["thresholds"] = th
		}
	}
	return opts, nil
}

// jsLiteral renders any value as a safe JS literal via JSON encoding.
func jsLiteral(v any) (string, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

var scriptTmpl = template.Must(template.New("k6").Funcs(template.FuncMap{
	"js": func(v any) (string, error) { return jsLiteral(v) },
}).Parse(`// Generated by apitool. Do not edit — regenerated on every run.
import http from 'k6/http';

export const options = {{ .OptionsJSON }};

const url = {{ js .URL }};
const params = { headers: {{ js .Headers }} };
{{ if .HasBody }}const body = {{ js .Body }};{{ end }}

export default function () {
  http.request({{ js .Method }}, url, {{ if .HasBody }}body{{ else }}null{{ end }}, params);
}

// handleSummary emits a delimited JSON blob to stdout that the runner parses
// as the authoritative end-of-test numbers (the live stream is approximate).
export function handleSummary(data) {
  const m = data.metrics || {};
  const dur = (m.http_req_duration && m.http_req_duration.values) || {};
  const reqs = (m.http_reqs && m.http_reqs.values) || {};
  const failed = (m.http_req_failed && m.http_req_failed.values) || {};

  const thresholds = [];
  for (const name of Object.keys(m)) {
    const t = m[name] && m[name].thresholds;
    if (!t) continue;
    for (const expr of Object.keys(t)) {
      thresholds.push({ metric: name, expression: expr, passed: t[expr].ok !== false });
    }
  }

  const summary = {
    requests: reqs.count || 0,
    rps: reqs.rate || 0,
    failRate: failed.rate || 0,
    durationAvgMs: dur.avg || 0,
    durationMinMs: dur.min || 0,
    durationMedMs: dur.med || 0,
    durationP90Ms: dur['p(90)'] || 0,
    durationP95Ms: dur['p(95)'] || 0,
    durationMaxMs: dur.max || 0,
    thresholdResults: thresholds,
  };
  return { stdout: '` + summaryStart + `' + JSON.stringify(summary) + '` + summaryEnd + `\n' };
}
`))

// decodeSummary extracts and parses the delimited handleSummary blob from a
// captured stdout buffer.
func decodeSummary(stdout []byte) (*perfSummary, error) {
	start := bytes.Index(stdout, []byte(summaryStart))
	end := bytes.Index(stdout, []byte(summaryEnd))
	if start < 0 || end < 0 || end < start {
		return nil, fmt.Errorf("k6 summary markers not found in output")
	}
	raw := stdout[start+len(summaryStart) : end]
	var s perfSummary
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, fmt.Errorf("parse k6 summary: %w", err)
	}
	return &s, nil
}

type perfSummary struct {
	Requests         int64                       `json:"requests"`
	RPS              float64                     `json:"rps"`
	FailRate         float64                     `json:"failRate"`
	DurationAvgMs    float64                     `json:"durationAvgMs"`
	DurationMinMs    float64                     `json:"durationMinMs"`
	DurationMedMs    float64                     `json:"durationMedMs"`
	DurationP90Ms    float64                     `json:"durationP90Ms"`
	DurationP95Ms    float64                     `json:"durationP95Ms"`
	DurationMaxMs    float64                     `json:"durationMaxMs"`
	ThresholdResults []model.PerfThresholdResult `json:"thresholdResults"`
}
