// Package mockserver serves a workspace's RECORDED responses back over a
// local HTTP endpoint, so a frontend team can build against an API that
// doesn't exist yet (or is down) without standing up a fake by hand.
//
// The data source is the store's last-response cache — the same one
// response()-chaining reads (storage.FileStore.LastResponse). Send a request
// once in AUK and it becomes a mock; re-send it and the mock updates on the
// next hit, because the route table is derived LIVE from the store on every
// incoming request rather than snapshotted at start (see DeriveRoutes).
//
// Shape deliberately mirrors internal/mcpserver's embedded HTTP endpoint:
// loopback-only http.Server, started with a Start* constructor, stopped with
// Stop, with the GUI holding the handle and rendering a status struct in
// Settings. The one difference is auth: the MCP endpoint is bearer-gated
// because it can DRIVE the app, while this one is a read-only replay of data
// the user explicitly recorded and explicitly chose to serve.
//
// # Origin policy (why this is not wide open)
//
// The mock replays REAL recorded traffic — access tokens, refresh tokens,
// Set-Cookie headers, customer records: whatever the team actually sent
// through AUK. A browser will read a cross-origin response body only when the
// server says so, so the header this file sets is the ONLY thing standing
// between that data and any page the developer happens to have open. An
// `Access-Control-Allow-Origin: *` would mean an ad frame or a random CodePen
// in another tab could `fetch('http://127.0.0.1:8725/oauth/token')` and read
// the reply. So:
//
//   - Allow-Origin is REFLECTED, never `*`, and only for a LOOPBACK origin
//     (http/https on localhost, 127.0.0.0/8, or ::1, any port). That is the
//     real use case — a Vite/CRA/Next dev server on localhost:5173 — and it
//     is the whole of it.
//   - Any other origin (https://evil.test, a page on the LAN, `Origin: null`
//     from a sandboxed frame or file://) gets NO CORS headers at all, on the
//     actual request AND on the preflight. The browser then blocks the read,
//     which is the correct outcome; the mock never has to guess.
//   - Allow-Credentials is never sent. The mock authenticates nobody, so a
//     page has no business attaching the developer's cookies to it.
//   - Expose-Headers is a short explicit list (corsExposedHeaders), not `*`,
//     so a replayed response header is not automatically readable script-side.
//   - Vary: Origin is always sent, because the answer genuinely differs by
//     Origin — including the no-headers answer.
//   - The listener binds 127.0.0.1 only (see Start), and every request's Host
//     header must itself be loopback (see hostAllowed) so a DNS-rebinding name
//     resolving to 127.0.0.1 cannot be used to reach the mock under an
//     attacker's origin.
//
// A non-browser client (curl, a server-side fetch, a same-origin request)
// sends no Origin, gets no CORS headers, and is unaffected by any of this —
// the browser is the only thing these headers speak to.
package mockserver

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"apitool/internal/core/model"
)

// DefaultPort is the fixed loopback port the mock listens on unless the user
// picks another. Fixed rather than ephemeral so a frontend's `.env` pointing
// at http://127.0.0.1:8725 keeps working across app restarts. One above the
// embedded MCP server's 8724, to keep AUK's two local endpoints adjacent.
const DefaultPort = 8725

// MockHeader is set on EVERY response the mock produces — replays, 404s,
// 405s, preflights — so a confused frontend can tell "this came from the AUK
// mock" from "this came from the real API" with one glance at devtools.
const MockHeader = "X-AUK-Mock"

// shutdownTimeout bounds Stop, matching internal/mcpserver's.
const shutdownTimeout = 3 * time.Second

// skipHeaders are recorded response headers that must NOT be copied onto the
// replay, keyed lowercase.
//
//   - hop-by-hop headers (RFC 9110 §7.6.1) describe the ORIGINAL connection
//     and are meaningless (Connection, Keep-Alive, TE, Trailer, Upgrade,
//     Proxy-*) or actively corrupting (Transfer-Encoding: chunked on a
//     response net/http will frame itself) on this one;
//   - Content-Length is recomputed from the bytes actually written;
//   - Date is regenerated by net/http, since replaying a timestamp from
//     whenever the request was recorded would feed browser cache heuristics
//     a lie;
//   - Access-Control-* is owned by this server. Copying a recorded CORS
//     header would emit TWO Access-Control-Allow-Origin values, which every
//     browser rejects outright — the one failure mode that would break the
//     exact use case this feature exists for;
//   - X-AUK-Mock is ours (a mock of a mock would otherwise stack values).
//
// Content-Encoding is deliberately NOT stripped: net/http's transport removes
// that header when it transparently decompresses, so if it survived into the
// recording the stored bytes really are still encoded, and replaying the
// header with them is the faithful thing to do.
var skipHeaders = map[string]bool{
	"connection":          true,
	"keep-alive":          true,
	"proxy-authenticate":  true,
	"proxy-authorization": true,
	"te":                  true,
	"trailer":             true,
	"transfer-encoding":   true,
	"upgrade":             true,
	"content-length":      true,
	"date":                true,
	"x-auk-mock":          true, // lowercase MockHeader
}

// allowedMethods is advertised on preflights. The mock will replay whatever
// method a request was recorded with; this list is just the browser-facing
// promise, kept broad so a preflight never blocks a call the mock could
// actually serve.
const allowedMethods = "GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS"

// corsExposedHeaders is the conservative allowlist of response headers a
// cross-origin page may READ off a mock reply, replacing an earlier `*`.
// `*` made every REPLAYED header script-readable — a recorded API's
// X-Auth-Token, X-Customer-Id, rate-limit internals and the rest — for no
// benefit, since the frontend the mock exists for only ever needs the
// content type, the length, the 405's Allow, and the marker that says the
// answer came from the mock. Note the CORS-safelisted response headers
// (Content-Type, Content-Length, …) are readable regardless; listing them is
// documentation, not permission.
const corsExposedHeaders = "Content-Type, Content-Length, Allow, " + MockHeader

// defaultAllowHeaders answers a preflight that named no request headers.
// Only meaningful on a preflight, and deliberately a short concrete list
// rather than `*`.
const defaultAllowHeaders = "Content-Type, Authorization, Accept"

// Server is a running mock endpoint for ONE workspace.
type Server struct {
	store       Store
	workspaceID string
	port        int
	srv         *http.Server
}

// Start binds a loopback listener and serves the workspace's recorded
// responses. port 0 picks a free ephemeral port (what tests use); callers
// that want the stable default pass DefaultPort.
//
// Loopback-only, always: 127.0.0.1 rather than :port, so a mock full of a
// team's real recorded API responses is never reachable from the network the
// laptop happens to be on.
func Start(store Store, workspaceID string, port int) (*Server, error) {
	if store == nil {
		return nil, errors.New("mock server: store is required")
	}
	if strings.TrimSpace(workspaceID) == "" {
		return nil, errors.New("mock server: a workspace must be selected")
	}
	if port < 0 || port > 65535 {
		return nil, fmt.Errorf("mock server: port %d out of range (1-65535)", port)
	}

	ln, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return nil, fmt.Errorf("mock server: listen on port %d: %w", port, err)
	}

	s := &Server{store: store, workspaceID: workspaceID, port: ln.Addr().(*net.TCPAddr).Port}
	s.srv = &http.Server{Handler: s, ReadHeaderTimeout: 10 * time.Second}
	go func() {
		// ErrServerClosed is the normal Stop path; a real bind failure has
		// already surfaced from net.Listen above.
		_ = s.srv.Serve(ln)
	}()
	return s, nil
}

// Port is the port actually bound (resolved, when Start was given 0).
func (s *Server) Port() int { return s.port }

// WorkspaceID is the workspace being served.
func (s *Server) WorkspaceID() string { return s.workspaceID }

// URL is the base address to point a frontend at.
func (s *Server) URL() string { return fmt.Sprintf("http://127.0.0.1:%d", s.port) }

// Routes returns the CURRENT route table, read live from the store.
func (s *Server) Routes() []Route { return DeriveRoutes(s.store, s.workspaceID) }

// Stop shuts the endpoint down. Safe to call on an already-stopped server.
func (s *Server) Stop() {
	if s == nil || s.srv == nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()
	_ = s.srv.Shutdown(ctx)
}

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h := w.Header()
	// CORS and the mock marker are decided FIRST, so they're present on error
	// responses too — a frontend debugging a 404 from the mock must be able to
	// read that 404, not have it hidden behind a CORS failure. "Present" here
	// means "present for an allowed origin": setCORS emits nothing at all for
	// an origin that isn't loopback, on errors exactly as on replays.
	setCORS(h, r)
	h.Set(MockHeader, "1")

	// DNS-rebinding defense. The listener is bound to 127.0.0.1, but that
	// only constrains the ROUTE, not the NAME: an attacker can point
	// mock.evil.test at 127.0.0.1, serve a page from that name, and their
	// script's requests then arrive here as same-origin (no Origin header, no
	// CORS check to fail). Requiring the Host header itself to be a loopback
	// name closes that, because a rebound request carries the attacker's
	// hostname. Checked before routing so a rejected host never reaches the
	// store, and never gets the 404/405/200 path-enumeration oracle either.
	if !hostAllowed(r.Host) {
		writeError(w, http.StatusForbidden,
			"mock server: request Host is not a loopback address",
			"the mock is loopback-only; reach it at 127.0.0.1 or localhost")
		return
	}

	// A CORS preflight is answered by the mock itself and never routed: the
	// browser sends OPTIONS with no body and expects headers only, so
	// replaying some recorded OPTIONS response here would be wrong even if
	// one existed. A plain OPTIONS (no preflight header) falls through to
	// normal routing, so an OPTIONS endpoint that WAS recorded still works.
	if r.Method == http.MethodOptions && r.Header.Get("Access-Control-Request-Method") != "" {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	routes := s.Routes()
	method := strings.ToUpper(r.Method)
	path := normalizePath(r.URL.Path)

	route, ok, allow := Match(routes, method, path)
	if !ok && method == http.MethodHead {
		// HEAD is served from the GET recording (net/http suppresses the body
		// for us) rather than 405'd — the standard HTTP courtesy, and nobody
		// records a HEAD request by hand.
		route, ok, _ = Match(routes, http.MethodGet, path)
	}
	if !ok {
		if len(allow) > 0 {
			h.Set("Allow", strings.Join(allow, ", "))
			writeError(w, http.StatusMethodNotAllowed,
				fmt.Sprintf("no mock for %s %s", method, path),
				"recorded for this path: "+strings.Join(allow, ", "))
			return
		}
		writeError(w, http.StatusNotFound,
			fmt.Sprintf("no mock for %s %s", method, path),
			"send the request once in AUK to record a mock")
		return
	}

	// Re-read the response by request id rather than caching it on the Route:
	// between deriving the table and here, a send in the app may have
	// replaced it, and serving the newest recording is the point.
	resp, found := s.store.LastResponse(route.RequestID)
	if !found || resp.Status <= 0 {
		writeError(w, http.StatusNotFound,
			fmt.Sprintf("no mock for %s %s", method, path),
			"send the request once in AUK to record a mock")
		return
	}
	replay(w, r, resp)
}

// setCORS makes the mock usable from a browser app on any LOOPBACK port —
// a Vite/CRA/Next dev server on localhost:5173, which is the entire reason
// this feature exists — and from nowhere else. See the package doc for why.
//
// The origin is reflected rather than wildcarded, and reflected ONLY after
// isLoopbackOrigin approves it. Any other origin gets no CORS headers, which
// is not an error the mock reports: the browser simply refuses to hand the
// body to the calling script, which is the whole point. Allow-Credentials is
// never set, so even an allowed loopback page cannot attach cookies.
func setCORS(h http.Header, r *http.Request) {
	// Vary goes on unconditionally, including on the no-headers answer: the
	// response genuinely differs by Origin, so any cache between here and a
	// browser must key on it — otherwise a cached "allowed" reply for
	// localhost:5173 could be served to a page that was never allowed.
	h.Add("Vary", "Origin")
	h.Add("Vary", "Access-Control-Request-Headers")

	origin := strings.TrimSpace(r.Header.Get("Origin"))
	if origin == "" {
		// curl, a server-side client, or a same-origin fetch. No CORS
		// negotiation is happening; emitting allow headers would only be
		// noise.
		return
	}
	if !isLoopbackOrigin(origin) {
		return
	}

	h.Set("Access-Control-Allow-Origin", origin)
	h.Set("Access-Control-Allow-Methods", allowedMethods)
	// Echo whatever the preflight asked for, now that we know the asker is a
	// local dev server; otherwise a short concrete default.
	if want := r.Header.Get("Access-Control-Request-Headers"); want != "" {
		h.Set("Access-Control-Allow-Headers", want)
	} else {
		h.Set("Access-Control-Allow-Headers", defaultAllowHeaders)
	}
	h.Set("Access-Control-Expose-Headers", corsExposedHeaders)
	h.Set("Access-Control-Max-Age", "600")
}

// isLoopbackOrigin reports whether an Origin header value names a page served
// from this machine's loopback interface — the only kind of page allowed to
// read the mock's recorded data.
//
// `null` (a sandboxed iframe, a file:// document, some redirect chains) is
// NOT loopback: it is the origin every opaque context shares, so allowing it
// would allow all of them at once. Anything that isn't a bare
// scheme://host[:port] is rejected too, rather than guessed at.
func isLoopbackOrigin(origin string) bool {
	if origin == "" || strings.EqualFold(origin, "null") {
		return false
	}
	u, err := url.Parse(origin)
	if err != nil || u.Host == "" {
		return false
	}
	// A serialized origin has no userinfo, path, query or fragment. If this
	// one does, it isn't an origin — don't try to salvage it.
	if u.User != nil || u.Path != "" || u.RawQuery != "" || u.Fragment != "" {
		return false
	}
	switch strings.ToLower(u.Scheme) {
	case "http", "https":
		// https included because a dev server run with TLS (vite --https,
		// next dev --experimental-https) is still the same local page.
	default:
		return false
	}
	return isLoopbackHost(u.Hostname())
}

// isLoopbackHost reports whether a bare hostname is loopback: the literal
// name "localhost", or any IP in 127.0.0.0/8 / ::1.
//
// Only the exact name "localhost" — NOT "*.localhost". Browsers treat that
// suffix as potentially-trustworthy, but whether "evil.localhost" resolves to
// 127.0.0.1 is a resolver detail an attacker can influence, and the mock has
// no reason to accept a name it did not have to.
func isLoopbackHost(host string) bool {
	host = strings.ToLower(strings.TrimSpace(host))
	if host == "" {
		return false
	}
	if host == "localhost" {
		return true
	}
	// url.URL.Hostname already strips an IPv6 literal's brackets; a raw Host
	// header may not have, hence the Trim.
	if ip := net.ParseIP(strings.Trim(host, "[]")); ip != nil {
		return ip.IsLoopback()
	}
	return false
}

// hostAllowed reports whether a request's Host header targets the mock by a
// loopback name — the DNS-rebinding check described in the package doc.
//
// An absent Host is allowed: only an HTTP/1.0 client omits it, net/http has
// already accepted the connection on a 127.0.0.1-bound listener, and a
// browser (the only thing rebinding is aimed at) always sends one.
func hostAllowed(host string) bool {
	host = strings.TrimSpace(host)
	if host == "" {
		return true
	}
	if h, _, err := net.SplitHostPort(host); err == nil {
		return isLoopbackHost(h)
	}
	// No port (or a bracketless IPv6 literal SplitHostPort won't take).
	return isLoopbackHost(host)
}

// replay writes the recorded response back: its status, its headers minus the
// ones that describe the original connection, and its decoded body.
func replay(w http.ResponseWriter, r *http.Request, resp model.ResponseData) {
	// Decode BEFORE touching the header map, so the failure path below can
	// still write a clean error response instead of one wearing half the
	// recorded response's headers.
	body, err := base64.StdEncoding.DecodeString(resp.BodyBase64)
	if err != nil {
		// A corrupt recording is a mock problem, not the caller's fault — say
		// so with a 502 rather than serving garbage bytes.
		writeError(w, http.StatusBadGateway,
			"recorded response body could not be decoded",
			"re-send the request in AUK to re-record it")
		return
	}

	h := w.Header()
	for _, kv := range resp.Headers {
		name := strings.TrimSpace(kv.Key)
		if name == "" || skipHeaders[strings.ToLower(name)] {
			continue
		}
		if strings.HasPrefix(strings.ToLower(name), "access-control-") {
			continue
		}
		// Add, not Set: a response can legitimately repeat a header
		// (Set-Cookie above all), and collapsing those would lose data.
		// KeyValue.Enabled is ignored on purpose — response headers aren't
		// user-toggled rows, and honoring the flag would make a header from
		// any producer that leaves the bool at its zero value vanish.
		h.Add(name, kv.Value)
	}

	if !bodyAllowed(resp.Status) {
		w.WriteHeader(resp.Status)
		return
	}
	// Explicit Content-Length (recomputed, never the recorded one) so a HEAD
	// served off a GET recording still advertises the right size even though
	// net/http drops the body.
	h.Set("Content-Length", strconv.Itoa(len(body)))
	w.WriteHeader(resp.Status)
	if r.Method != http.MethodHead {
		_, _ = w.Write(body)
	}
}

// bodyAllowed reports whether a status code may carry a body at all —
// 1xx/204/304 may not, and framing one anyway is a protocol error.
func bodyAllowed(status int) bool {
	switch {
	case status >= 100 && status < 200:
		return false
	case status == http.StatusNoContent, status == http.StatusNotModified:
		return false
	}
	return true
}

// errorBody is what the mock returns when it has nothing to replay. JSON,
// because the caller is a frontend doing fetch().json() and an HTML error page
// would blow up in its parser.
type errorBody struct {
	Error string `json:"error"`
	Hint  string `json:"hint,omitempty"`
}

func writeError(w http.ResponseWriter, status int, msg, hint string) {
	payload, err := json.Marshal(errorBody{Error: msg, Hint: hint})
	if err != nil {
		payload = []byte(`{"error":"mock server error"}`)
	}
	h := w.Header()
	h.Set("Content-Type", "application/json; charset=utf-8")
	h.Set("Content-Length", strconv.Itoa(len(payload)))
	w.WriteHeader(status)
	_, _ = w.Write(payload)
}
