import { test } from "node:test";
import assert from "node:assert/strict";
import { canonicalBytes, licenseJSON, rfc3339Seconds } from "../src/canonical.js";

// The fixture below is generated by Go — see worker/scripts/dump-canonical.go
// and internal/license/worker_compat_test.go. If this test fails, the two
// implementations of the signing scheme have drifted and every licence this
// worker mints would be rejected by the app.
const FIXTURE = {
  licenseKey: "AUK-4KDR2-8QW1M-VZ0PT-N7C93",
  email: "vector@auk.test",
  name: "Vector Test",
  plan: "personal",
  machineId: "hw-fixturemachine00000000000000",
  maxMachines: 3,
  machineCount: 1,
  issuedAt: new Date("2026-08-31T10:04:05Z"),
  expiresUpdatesAt: new Date("2027-08-31T10:04:05Z"),
};

test("canonical bytes start with the domain-separation tag", () => {
  const out = canonicalBytes(FIXTURE);
  assert.equal(new TextDecoder().decode(out.subarray(0, 15)), "AUK-LICENSE-v1\n");
});

test("fields are length-prefixed big-endian, not delimited", () => {
  const out = canonicalBytes({ ...FIXTURE, licenseKey: "AB" });
  // tag(15) then a uint32 length of 2 then "AB"
  assert.deepEqual(Array.from(out.subarray(15, 19)), [0, 0, 0, 2]);
  assert.equal(new TextDecoder().decode(out.subarray(19, 21)), "AB");
});

test("sub-second precision cannot change the signed bytes", () => {
  // A JSON round trip routinely adds or drops milliseconds. If those reached
  // the signed bytes, a licence would verify at issue time and fail after
  // being stored and reloaded.
  const withMillis = { ...FIXTURE, issuedAt: new Date("2026-08-31T10:04:05.937Z") };
  assert.deepEqual(canonicalBytes(withMillis), canonicalBytes(FIXTURE));
});

test("a field boundary cannot be forged from field contents", () => {
  // Two different licences whose concatenated content is identical must still
  // produce different signed bytes — that is exactly what length prefixes buy.
  const a = canonicalBytes({ ...FIXTURE, email: "ab", name: "c" });
  const b = canonicalBytes({ ...FIXTURE, email: "a", name: "bc" });
  assert.notDeepEqual(a, b);
});

test("rfc3339Seconds matches Go's time.RFC3339 rendering", () => {
  assert.equal(rfc3339Seconds(new Date("2026-08-31T10:04:05.937Z")), "2026-08-31T10:04:05Z");
  assert.equal(rfc3339Seconds(new Date("2026-01-01T00:00:00.000Z")), "2026-01-01T00:00:00Z");
});

test("licenseJSON emits the same second-precision times that were signed", () => {
  const j = licenseJSON({ ...FIXTURE, issuedAt: new Date("2026-08-31T10:04:05.937Z") });
  assert.equal(j.issuedAt, "2026-08-31T10:04:05Z");
  assert.equal(j.maxMachines, 3);
  assert.equal(j.machineId, FIXTURE.machineId);
});
