// Licensing + trial state for the frontend. Mirrors internal/license.Status
// (Go) 1:1 and wraps the four Wails bindings in app_license.go.
//
// Why the bindings are reached via window.go.main.App rather than the usual
// import from ../../wailsjs/go/main/App: those wrappers are code-generated by
// `wails build`/`wails dev`, and the licensing methods only appear there after
// the next generation. Calling through the runtime object keeps this file
// type-checking and building TODAY (before that regeneration) and works
// unchanged after it — Wails exposes every bound method at
// window.go.<pkg>.<Struct>.<Method> regardless. This is deliberately the only
// file that does so; everything else uses the generated bindings.

import { createSignal } from 'solid-js'

/** The four licensing states — exactly one is ever `state`. */
export type LicenseState = 'trial' | 'licensed' | 'trial_expired' | 'license_invalid'

/** Mirror of internal/license.Status. Optional fields use Go `omitempty`. */
export interface LicenseStatus {
  state: LicenseState
  /** Trial days left when state is 'trial'; 0 otherwise. */
  daysRemaining: number
  email?: string
  name?: string
  plan?: string
  machineCount?: number
  maxMachines?: number
  machineId?: string
  /** Past the 12-month updates window. App still runs — advisory only. */
  updatesExpired?: boolean
  updatesExpireAt?: string
  /** Within the 30-day online-recheck grace window. Advisory only. */
  inGrace?: boolean
  graceDaysRemaining?: number
  /** Short human-readable note (invalid reason, updates-expired notice, …). */
  message?: string
}

/** The subset of App bindings this module calls. */
interface LicenseBindings {
  LicenseStatus(): Promise<LicenseStatus>
  ActivateLicense(key: string): Promise<LicenseStatus>
  DeactivateLicense(): Promise<LicenseStatus>
  StartTrialIfNeeded(): Promise<LicenseStatus>
}

function app(): Partial<LicenseBindings> {
  const w = window as unknown as { go?: { main?: { App?: Partial<LicenseBindings> } } }
  return w.go?.main?.App ?? {}
}

const UNAVAILABLE = 'Licensing is unavailable in this build.'

// Current status. `null` means "not loaded yet" — components should render a
// neutral/empty state for null rather than assuming trial or licensed.
const [status, setStatus] = createSignal<LicenseStatus | null>(null)

/** Reactive accessor for the current license status (null until loaded). */
export const licenseStatus = status

/** Convenience derivations for gating/display. */
export const isLicensed = (): boolean => status()?.state === 'licensed'
export const isTrial = (): boolean => status()?.state === 'trial'
export const isTrialExpired = (): boolean => status()?.state === 'trial_expired'

/**
 * Loads the current status and, on first ever launch, records the trial start.
 * A single call is enough on app mount: StartTrialIfNeeded is idempotent and
 * returns the resulting status. Falls back to a plain status read if that
 * binding isn't present. Never throws — a failure leaves status null.
 */
export async function initLicense(): Promise<void> {
  const a = app()
  try {
    if (a.StartTrialIfNeeded) {
      setStatus(await a.StartTrialIfNeeded())
    } else if (a.LicenseStatus) {
      setStatus(await a.LicenseStatus())
    }
  } catch (e) {
    console.error('license: init failed', e)
  }
}

/** Re-reads status from the backend (e.g. after returning from a purchase). */
export async function refreshLicense(): Promise<void> {
  const a = app()
  if (!a.LicenseStatus) return
  try {
    setStatus(await a.LicenseStatus())
  } catch (e) {
    console.error('license: refresh failed', e)
  }
}

/** Result of an activate/deactivate attempt, for inline UI feedback. */
export interface LicenseActionResult {
  ok: boolean
  error?: string
  status?: LicenseStatus
}

/**
 * Activates a pasted license key or signed license file. Updates the shared
 * signal on success and returns a structured result so the UI can show inline
 * success/error without a second round trip.
 */
export async function activate(key: string): Promise<LicenseActionResult> {
  const a = app()
  if (!a.ActivateLicense) return { ok: false, error: UNAVAILABLE }
  try {
    const st = await a.ActivateLicense(key)
    setStatus(st)
    if (st.state === 'licensed') return { ok: true, status: st }
    // The binding throws on rejection, so a non-licensed return here is
    // unusual — surface its message defensively.
    return { ok: false, status: st, error: st.message || 'Activation did not complete.' }
  } catch (e) {
    return { ok: false, error: errorMessage(e) }
  }
}

/** Removes the license from this machine, returning to the trial. */
export async function deactivate(): Promise<LicenseActionResult> {
  const a = app()
  if (!a.DeactivateLicense) return { ok: false, error: UNAVAILABLE }
  try {
    const st = await a.DeactivateLicense()
    setStatus(st)
    return { ok: true, status: st }
  } catch (e) {
    return { ok: false, error: errorMessage(e) }
  }
}

// Wails rejects a bound-method promise with the Go error's message, which may
// arrive as a bare string or an Error depending on the runtime path.
function errorMessage(e: unknown): string {
  if (typeof e === 'string') return e
  if (e instanceof Error) return e.message
  return String(e)
}
